name: Nightly Data Update

permissions: write-all

on:
  schedule:
    # Runs at midnight UTC
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update_data:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI SKIP]')"
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🔨 Run the script
        run: bash backup.sh readme-only
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update data [CI SKIP]"
          committer_name: GitHub Actions
          committer_email: action@github.com
